// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Test', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1330, height: 824 })
    await driver.findElement(By.name("name")).click()
    await driver.findElement(By.name("name")).sendKeys("Mame Aicha")
    await driver.findElement(By.name("surname")).click()
    await driver.findElement(By.name("surname")).sendKeys("Dieye")
    await driver.findElement(By.name("identifiant")).click()
    await driver.findElement(By.name("identifiant")).sendKeys("20211027")
    await driver.findElement(By.name("envoyer")).click()
    assert(await driver.switchTo().alert().getText() == "SUCCESS")
  })
})
